-- 코드를 입력하세요
# SELECT TITLE, BOARD_ID FROM USED_GOODS_BOARD WHERE CREATED_DATE BETWEEN "2022-10-01" AND "2022-10-31"
# REPLY_ID, WRITER_ID, CONTENTS, CREATED_DATE

SELECT TITLE, a.BOARD_ID, REPLY_ID, a.WRITER_ID, a.CONTENTS, DATE_FORMAT(a.CREATED_DATE, "%Y-%m-%d") AS CREATED_DATE
FROM USED_GOODS_REPLY a
INNER JOIN USED_GOODS_BOARD b
ON a.BOARD_ID = b.BOARD_ID
WHERE b.CREATED_DATE BETWEEN "2022-10-01" AND "2022-10-31"
ORDER BY a.CREATED_DATE ASC, TITLE ASC